spring:
  application:
    name: spring-matrix-161

  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mj_161
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none


secret:
  key: my_secret_key

employee:
  client-url: http://localhost:8081/employee