create table customers
(
    id  bigint generated by default as identity
        primary key,
    email   varchar(255),
    name    varchar(255),
    status  boolean,
    surname varchar(255)
);

alter table customers
    owner to postgres;

